### ISSUE TITLE
Consolidate assets that are Skyrim version independent

### ISSUE THREAD

**Issue by ThisIsPatrick** [SkyrimLL/Skyrim#55]
Some specific mod assets are no different for in all versions of Skyrim, and thus don't need to be duplicated into both sections.
These could moved to a single folder, to make maintaining the repo easier and cut down on repo size.

The following are version independent:
Interface folder
SEQ files
StorageUtilData folder
PEX/PSC files (scripts)
Sounds folder

Textures - Unless the saved compression format is BC7 (BC7 is exclusive to SE)
ESP plugins - Unless the plugin is specifically meant for a LE/SE mod or has the ESL flag set (the ESL flag is exclusive to SE.) Form 43/44 differences shouldn't be a problem.

**Comment by SkyrimLL** [comment]
I made the choice of two branches more out of personal laziness than for optimization purposes.
Having a shared resource between the two versions would have me keep things in 3 places - one LE specific folder, one SE specific folder and one shared. I find it easier for my sanity to keep things only in two places when it comes to assembling the mods for publication :)
I have a deployment script that keeps them synchronized so I won't be missing anything.
